In [1]:
import pandas as pd
from evidently import Dataset
from evidently import DataDefinition
from evidently import Report
from evidently.presets import TextEvals
from evidently.tests import lte, gte, eq
from evidently.descriptors import LLMEval, TestSummary, DeclineLLMEval, Sentiment, TextLength, IncludesWords
from evidently.llm.templates import BinaryClassificationPromptTemplate
from evidently.ui.workspace import CloudWorkspace

## Configuration credential

In [2]:
# Configuration for the credential
import os
from dotenv import load_dotenv

ENV_PATH = ".env"
load_dotenv(ENV_PATH)

False

## Create project on evidently AI

In [3]:
ws = CloudWorkspace(token=os.getenv("EVIDENTLY_TOKEN"), url="https://app.evidently.cloud")

## Create a Project within your Organization, or connect to an existing Project:

In [4]:
try:
    existing_projects = ws.list_projects()
    project = next((p for p in existing_projects if p.name == "LLM Audit"), None)
    
    if project is None:
        project = ws.create_project(name="LLM Audit", org_id="019d6885-06c6-7601-9a3e-2298bed991f4")
        project.description = "Project for auditing LLM performance on models, data, and LLMs evaluations."
        project.save()
        print(f"✅ Project created: {project.name}")   # ← print, not project()
    else:
        print(f"📁 Project already exists: {project.name}")  # ← print, not project()

except Exception as e:
    print(f"Error accessing or creating project: {e}")

print(f"Project name: {project.name}")

📁 Project already exists: LLM Audit
Project name: LLM Audit

## Prepare the dataset -> Merge prompt with dataframe into reliable data information
* ### Load dataset
* ### Create prompt

## Load dataset

In [5]:
pd.set_option('display.max_columns', None)
df = pd.read_parquet("../../Database/data/eda_banking.parquet")
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned,Fraud,RiskScore,BalancePerProduct,AgeRisk,HighValueCustomer,LowCreditRisk,MarketingScore,ComplainFlag,LowSatisfaction,OperationalRiskScore
0,619,France,Female,42,2,11983969.0,1,1,1,10134888.0,1,1,2,DIAMOND,464,0,1,0.000000,0,0,0,0,1,1,2
1,608,Spain,Female,41,1,8380786.0,1,0,1,11254258.0,0,1,3,DIAMOND,456,0,1,41903.930000,0,0,0,1,1,0,1
2,502,France,Female,42,8,15966080.0,3,1,0,11393157.0,1,1,3,DIAMOND,377,0,3,39915.200000,0,1,0,1,1,0,2
3,699,France,Female,39,1,11983969.0,2,0,0,9382663.0,0,0,5,GOLD,350,0,1,0.000000,0,0,0,0,0,0,1
4,850,Spain,Female,43,2,12551082.0,1,1,1,7908410.0,0,0,5,GOLD,425,0,1,62755.410000,0,1,0,2,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,11983969.0,2,1,0,9627064.0,0,0,1,DIAMOND,300,0,1,0.000000,0,0,0,0,0,1,2
9996,516,France,Male,35,10,5736961.0,1,1,1,10169977.0,0,0,5,PLATINUM,771,0,0,28684.805000,0,0,0,0,0,0,0
9997,709,France,Female,36,7,11983969.0,1,0,1,4208558.0,1,1,3,SILVER,564,0,1,0.000000,0,0,0,0,1,0,1
9998,772,Germany,Male,42,3,7507531.0,2,1,0,9288852.0,1,1,2,GOLD,339,1,2,25025.103333,0,0,0,1,1,1,3
9999,792,France,Female,28,4,13014279.0,1,1,0,3819078.0,0,0,3,DIAMOND,911,0,2,65071.395000,0,1,0,1,0,0,1

## Create LLMs prompt for evidentlyAI production

In [6]:
# Define questions and context
question_and_context = [
    [
        "What is the fraud detection rate in the dataset?",
        "Fraud detection in banking uses ML classifiers. Precision-recall tradeoffs are critical."
    ],
    [
        "Which ML model performs best for credit default prediction?",
        "XGBoost and Random Forest outperform logistic regression on imbalanced datasets."
    ],
    [
        "How should missing values be handled in operational banking data?",
        "Imputation must preserve regulatory compliance and not introduce synthetic bias."
    ],
    [
        "What is the churn rate and how can it be reduced?",
        "Customer churn in retail banking averages 15-20% annually."
    ],
    [
        "Explain the class imbalance issue in fraud detection.",
        "Fraud datasets are heavily imbalanced with fraud rates below 1-2%."
    ],
]

pd.set_option('display.max_colwidth', None)
eval_df = pd.DataFrame(question_and_context, columns=["question", "context"])

In [7]:
eval_df.head()

,question,context
0,What is the fraud detection rate in the dataset?,Fraud detection in banking uses ML classifiers. Precision-recall tradeoffs are critical.
1,Which ML model performs best for credit default prediction?,XGBoost and Random Forest outperform logistic regression on imbalanced datasets.
2,How should missing values be handled in operational banking data?,Imputation must preserve regulatory compliance and not introduce synthetic bias.
3,What is the churn rate and how can it be reduced?,Customer churn in retail banking averages 15-20% annually.
4,Explain the class imbalance issue in fraud detection.,Fraud datasets are heavily imbalanced with fraud rates below 1-2%.

In [8]:
from groq import Groq
import warnings
warnings.filterwarnings("ignore", category=UserWarning)

client = Groq(api_key=os.environ.get("GROQ_API_KEY_2"))

# 1. Build data context from dataframe
def build_data_context(df):
    context = f"""
You are a banking data analyst & data scentist. Use the following dataset information to reasong and answer questions.

DATASET OVERVIEW:
- Total Records: {len(df):,}
- Columns: {list(df.columns)}

STATISTICAL SUMMARY:
{df.describe().to_string()}

CATEGORICAL COLUMNS:
- Geography Distribution: {df['Geography'].value_counts().to_dict()}
- Gender Distribution: {df['Gender'].value_counts().to_dict()}
- Card Type Distribution: {df['Card Type'].value_counts().to_dict()}

- KEY METRICS:
- Fraud Rate: {df['Fraud'].mean():.2%}
- Churn Rate (Exited): {df['Exited'].mean():.2%}
- Avg Credit Score: {df['CreditScore'].mean():.2f}
- Avg Balance : {df['Balance'].mean():.2f}
- Avg Risk Score: {df['RiskScore'].mean():.2f}
- High Value Customers: {df['HighValueCustomer'].sum():,} ({df['HighValueCustomer'].mean():.2%})
- Customers with Complaints: {df['Complain'].sum():,} ({df['Complain'].mean():.2%})
- Active Members: {df['IsActiveMember'].sum():,} ({df['IsActiveMember'].mean():.2%})

CORRELATION WITH FRAUD (top features):
{df.corr(numeric_only=True)['Fraud'].sort_values(ascending=False).to_string()}

CORRELATION WITH CHURN (top features):
{df.corr(numeric_only=True)['Exited'].sort_values(ascending=False).to_string()}
"""
    
    return context

data_context = build_data_context(df)

In [9]:

# 2. Generate answers with data-aware prompting
def get_groq_response_with_context(row):
    prompt = f"""
{data_context}

---
CONTEXT HINT: {row['context']}
QUESTION: {row['question']}

Answer based strictly on the dataset statistics provided above. Be specific with numbers and percentages from the data.
"""
    
    completion = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7,
        max_tokens=1024,
        top_p=0.9,
        stream=False
    )
    return completion.choices[0].message.content

In [10]:
# apply to eval_df
eval_df['answer'] = eval_df.apply(get_groq_response_with_context, axis=1)
eval_df

                                                            question  \
0                   What is the fraud detection rate in the dataset?
1        Which ML model performs best for credit default prediction?
2  How should missing values be handled in operational banking data?
3                  What is the churn rate and how can it be reduced?
4              Explain the class imbalance issue in fraud detection.

                                                                                    context  \
0  Fraud detection in banking uses ML classifiers. Precision-recall tradeoffs are critical.
1          XGBoost and Random Forest outperform logistic regression on imbalanced datasets.
2          Imputation must preserve regulatory compliance and not introduce synthetic bias.
3                                Customer churn in retail banking averages 15-20% annually.
4                        Fraud datasets are heavily imbalanced with fraud rates below 1-2%.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  answer
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        To determine the fraud detection rate in the dataset, we need to look at the statistics provided. The fraud rate is explicitly mentioned in the KEY METRICS section:\n\n- Fraud Rate: 3.32%\n\nThis means that out of the total records (10,000), 3.32% of the customers are identified as fraudulent. To find the number of fraudulent customers, we can calculate:\n\nNumber of fraudulent customers = Total Records * Fraud Rate\n= 10,000 * 3.32%\n= 10,000 * 0.0332\n= 332\n\nSo, there are 332 customers identified as fraudulent in the dataset. The fraud detection rate, in this case, refers to the proportion of customers that are correctly identified as fraudulent out of all the customers that are actually fraudulent. However, the provided dataset does not explicitly give us the true positives (correctly identified fraudulent customers) versus false negatives (fraudulent customers not identified as such) to directly calculate the detection rate or the precision and recall of the fraud detection system.\n\nGiven the information available, we can only state the fraud rate as 3.32%, which indicates the prevalence of fraud in the dataset, not the performance of a fraud detection model. For a detailed analysis of the fraud detection rate (including precision, recall, and F1 score), we would need more specific information about the true positives, false positives, true negatives, and false negatives resulting from a fraud detection model's predictions.
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  To determine which ML model performs best for credit default prediction, we need to analyze the given dataset statistics. The problem of credit default prediction can be viewed as a classification problem where we aim to predict whether a customer will default on their credit (i.e., commit fraud) based on various features.\n\nGiven the dataset statistics, we notice that the target variable 'Fraud' has a rate of 3.32%, indicating an imbalanced dataset. In such cases, models like XGBoost and Random Forest tend to outperform logistic regression.\n\nFrom the correlation analysis with 'Fraud', we see that the top features correlated with fraud are 'Exited', 'ComplainFlag', 'Complain', 'OperationalRiskScore', and 'RiskScore', with correlation coefficients of 0.292838, 0.292243, 0.292243, 0.283743, and 0.223436, respectively.\n\nWhile the dataset statistics do not provide direct performance metrics (e.g., accuracy, precision, recall, F1-score, ROC-AUC) for different ML models, the hint provided suggests that XGBoost and Random Forest tend to outperform logistic regression on imbalanced datasets.\n\nBased on this information, we can infer that XGBoost and Random Forest are likely to perform better than logistic regression for credit default prediction. However, without explicit performance metrics, it's challenging to determine which one performs best between XGBoost and Random Forest.\n\nAssuming that the performance of these models follows the general trend observed in imbalanced datasets, we can make an educated guess. XGBoost, being an ensemble model that combines multiple weak models to create a strong predictive model, often performs well in handling imbalanced datasets and complex interactions between features.\n\nTherefore, based on the provided dataset statistics and the context hint, XGBoost is likely to be a top-performing model for credit default prediction, but the actual performance may vary depending on the specific implementation, hyperparameter tuning, and evaluation metrics used. \n\nTo give a more precise answer, we would need the results of the models' performance on a test set, which is not provided in the dataset statistics. However, if we had to choose based on the information given and general trends in machine learning, XGBoost would be a reasonable choice for handling the imbalanced 'Fraud' classification problem. \n\nIn terms of numbers, we know that 3.32% of the customers are fraudsters, and we have a total of 10,000 records. This translates to approximately 332 fraud cases (0.0332 * 10,000). The performance of the model would be evaluated based on its ability to correctly identify these 332 cases while minimizing false positives. \n\nGiven the imbalanced nature of the dataset, it's essential to use appropriate evaluation metrics, such as precision, recall, F1-score, and ROC-AUC, to assess the model's performance. However, without explicit results, we can only speculate about the relative performance of different models based on their characteristics and the dataset statistics provided.
2  To handle missing values in operational banking data while preserving regulatory compliance and avoiding synthetic bias, we should consider the characteristics of the data and the implications of different imputation strategies. Based on the provided dataset statistics:\n\n1. **Mean and Standard Deviation**: Many features have a relatively large standard deviation compared to their mean, indicating a potential for outliers and skewness in the data. This suggests that mean or median imputation might not be suitable for all features.\n\n2. **Distribution of Categorical Variables**: The distribution of categorical variables like Geography, Gender, and Card Type shows a mix of balanced and imbalanced classes. For example, Geography has a relatively balanced distribution (France: 50.14%, Germany: 25.09%, Spain: 24.77%), while Card Type is also somewhat balanced. This balance is important to maintain when imputing missing values to avoid introducing bias.\n\n3. **Correlation with Fraud and Churn**: The features most correlated with Fraud and Churn (Exited) are largely related to customer behavior and risk assessment (e.g., Exited, ComplainFlag, OperationalRiskScore, RiskScore). Imputation strategies should preserve these relationships to maintain the integrity of risk and churn models.\n\n4. **Key Metrics**: The dataset has a Fraud Rate of 3.32%, a Churn Rate of 20.38%, and an average Credit Score of 650.53. These metrics indicate the importance of accurately modeling customer behavior and risk.\n\nGiven these considerations, here are some strategies for handling missing values:\n\n- **Listwise Deletion**: For features with very few missing values (less than 1%), listwise deletion might be acceptable, especially if the missing values are missing completely at random (MCAR). However, this approach risks bias if the missing values are not MCAR.\n\n- **Mean/Median Imputation**: For numerical features with a relatively small standard deviation and no significant outliers (e.g., Age, with a mean of 38.92 and a standard deviation of 10.49), mean or median imputation could be appropriate. For example, imputing the mean Age (38.92) for missing Age values might be reasonable.\n\n- **Regression Imputation**: For features highly correlated with others (e.g., RiskScore with OperationalRiskScore), using a regression model to predict missing values based on correlated features could be effective. This method can help preserve the relationships between features.\n\n- **K-Nearest Neighbors (KNN) Imputation**: This method involves finding similar data points (based on other features) to a row with a missing value and imputing the missing value with the mean or median of those similar points. It can be particularly useful for categorical variables or when the relationship between features is complex.\n\n- **Multiple Imputation**: Creating multiple versions of the dataset with different imputations for missing values and then analyzing each version to account for the uncertainty introduced by imputation. This approach is more complex but provides a way to quantify the impact of missing data on analysis results.\n\nFor this dataset, given the regulatory compliance and bias avoidance requirements, a combination of these strategies could be employed, tailored to the specific characteristics of each feature. For instance:\n\n- For the 'CreditScore' feature, which has a mean of 650.53 and a standard deviation of 96.65, mean imputation might be suitable due to its central tendency and variability.\n- For 'Geography', given its categorical nature and the need to preserve class balance, a random imputation based on the observed class distribution (e.g., 50.14% France, 25.09% Germany, 24.77% Spain) could be used.\n- For features highly correlated with Fraud or Churn, like 'ComplainFlag' or 'RiskScore', regression imputation or KNN imputation could be more appropriate to maintain these critical relationships.\n\nUltimately, the choice of imputation method should be guided by the specific analysis goals, the nature of the missing data (MCAR, MAR, or MNAR), and the need to preserve regulatory compliance and avoid introducing synthetic bias.

## Auditing the LLMs for evaluation

* ###  Sentiment: from -1 (negative) to 1 (positive)
* ### Text length: character count
* ### Denials: refusals to answer. This uses an LLM-as-a-judge with built-in prompt.

### Each evaluation is a descriptor. It adds a new score or label to each row in your dataset. For LLM-as-a-judge, we’ll use OpenAI GPT-4o mini. Set OpenAI key as an environment variable:

In [11]:
# Turn on debug
import litellm

litellm._turn_on_debug()

os.environ["GROQ_API_KEY_2"] = os.environ.get("GROQ_API_KEY_2", "")

response = litellm.completion(
    model="groq/llama-3.1-8b-instant",
    messages=[{"role": "user", "content": "Say OK"}],
)
print(response.choices[0].message.content)

13:33:40 - LiteLLM:DEBUG: utils.py:481 -

13:33:40 - LiteLLM:DEBUG: utils.py:481 - Request to litellm:
13:33:40 - LiteLLM:DEBUG: utils.py:481 - litellm.completion(model='groq/llama-3.1-8b-instant', messages=[{'role': 'user', 'content': 'Say OK'}])
13:33:40 - LiteLLM:DEBUG: utils.py:481 -

13:33:40 - LiteLLM:DEBUG: utils.py:1007 - Removing thought signatures from tool call IDs for non-Gemini model
13:33:40 - LiteLLM:DEBUG: litellm_logging.py:557 - self.optional_params: {}
13:33:40 - LiteLLM:DEBUG: utils.py:481 - SYNC kwargs[caching]: False; litellm.cache: None; kwargs.get('cache')['no-cache']: False
13:33:40 - LiteLLM:DEBUG: utils.py:5605 - checking potential_model_names in litellm.model_cost: {'split_model': 'llama-3.1-8b-instant', 'combined_model_name': 'groq/llama-3.1-8b-instant', 'stripped_model_name': 'llama-3.1-8b-instant', 'combined_stripped_model_name': 'groq/llama-3.1-8b-instant', 'custom_llm_provider': 'groq'}
13:33:40 - LiteLLM:DEBUG: utils.py:5605 - checking potential_model_names in litellm.model_cost: {'split_model': 'llama-3.1-8b-instant', 'combined_model_name': 'groq/llama-3.1-8b-instant', 'stripped_model_name': 'llama-3.1-8b-instant', 'combined_stripped_model_name': 'groq/llama-3.1-8b-instant', 'custom_llm_provider': 'groq'}
13:33:40 - LiteLLM:INFO: utils.py:4004 -
LiteLLM completion() model= llama-3.1-8b-instant; provider = groq
13:33:40 - LiteLLM:DEBUG: utils.py:4007 -
LiteLLM: Params passed to completion() {'model': 'llama-3.1-8b-instant', 'functions': None, 'function_call': None, 'temperature': None, 'top_p': None, 'n': None, 'stream': None, 'stream_options': None, 'stop': None, 'max_tokens': None, 'max_completion_tokens': None, 'modalities': None, 'prediction': None, 'audio': None, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': None, 'user': None, 'custom_llm_provider': 'groq', 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None, 'max_retries': None, 'logprobs': None, 'top_logprobs': None, 'extra_headers': None, 'api_version': None, 'parallel_tool_calls': None, 'drop_params': None, 'allowed_openai_params': None, 'reasoning_effort': None, 'verbosity': None, 'additional_drop_params': None, 'messages': [{'role': 'user', 'content': 'Say OK'}], 'thinking': None, 'web_search_options': None, 'safety_identifier': None, 'service_tier': None}
13:33:40 - LiteLLM:DEBUG: utils.py:4010 -
LiteLLM: Non-Default params passed to completion() {}
13:33:40 - LiteLLM:DEBUG: utils.py:5605 - checking potential_model_names in litellm.model_cost: {'split_model': 'llama-3.1-8b-instant', 'combined_model_name': 'groq/llama-3.1-8b-instant', 'stripped_model_name': 'llama-3.1-8b-instant', 'combined_stripped_model_name': 'groq/llama-3.1-8b-instant', 'custom_llm_provider': 'groq'}
13:33:40 - LiteLLM:DEBUG: utils.py:481 - Final returned optional params: {'extra_body': {}}
13:33:40 - LiteLLM:DEBUG: litellm_logging.py:557 - self.optional_params: {'extra_body': {}}
13:33:40 - LiteLLM:DEBUG: utils.py:5605 - checking potential_model_names in litellm.model_cost: {'split_model': 'llama-3.1-8b-instant', 'combined_model_name': 'groq/llama-3.1-8b-instant', 'stripped_model_name': 'llama-3.1-8b-instant', 'combined_stripped_model_name': 'groq/llama-3.1-8b-instant', 'custom_llm_provider': 'groq'}
13:33:40 - LiteLLM:DEBUG: litellm_logging.py:1150 -

POST Request Sent from LiteLLM:
curl -X POST \
https://api.groq.com/openai/v1/chat/completions \
-H 'Authorization: Be****xS' -H 'Content-Type: application/json' \
-d '{'model': 'llama-3.1-8b-instant', 'messages': [{'role': 'user', 'content': 'Say OK'}]}'


13:33:40 - LiteLLM:DEBUG: litellm_logging.py:1223 - RAW RESPONSE:
{"id": "chatcmpl-c4d236ff-8fbf-4773-8834-fae898740161", "object": "chat.completion", "created": 1775799220, "model": "llama-3.1-8b-instant", "choices": [{"index": 0, "message": {"role": "assistant", "content": "OK."}, "logprobs": null, "finish_reason": "stop"}], "usage": {"queue_time": 0.043744788, "prompt_tokens": 37, "prompt_time": 0.002498112, "completion_tokens": 3, "completion_time": 0.009270671, "total_tokens": 40, "total_time": 0.011768783}, "usage_breakdown": null, "system_fingerprint": "fp_4387d3edbb", "x_groq": {"id": "req_01knty3egdf21aph1k5rpfan5t", "seed": 413517284}, "service_tier": "on_demand"}


13:33:40 - LiteLLM:INFO: utils.py:1652 - Wrapper: Completed Call, calling success_handler
13:33:40 - LiteLLM:DEBUG: litellm_logging.py:1991 - Logging Details LiteLLM-Success Call: Cache_hit=None
13:33:40 - LiteLLM:DEBUG: cost_calculator.py:1130 - selected model name for cost calculation: groq/llama-3.1-8b-instant
13:33:40 - LiteLLM:DEBUG: cost_calculator.py:1130 - selected model name for cost calculation: groq/llama-3.1-8b-instant
13:33:40 - LiteLLM:DEBUG: utils.py:5605 - checking potential_model_names in litellm.model_cost: {'split_model': 'llama-3.1-8b-instant', 'combined_model_name': 'groq/llama-3.1-8b-instant', 'stripped_model_name': 'llama-3.1-8b-instant', 'combined_stripped_model_name': 'groq/llama-3.1-8b-instant', 'custom_llm_provider': 'groq'}
13:33:40 - LiteLLM:DEBUG: utils.py:5605 - checking potential_model_names in litellm.model_cost: {'split_model': 'llama-3.1-8b-instant', 'combined_model_name': 'groq/llama-3.1-8b-instant', 'stripped_model_name': 'llama-3.1-8b-instant', 'combined_stripped_model_name': 'groq/llama-3.1-8b-instant', 'custom_llm_provider': 'groq'}
13:33:40 - LiteLLM:DEBUG: utils.py:5605 - checking potential_model_names in litellm.model_cost: {'split_model': 'llama-3.1-8b-instant', 'combined_model_name': 'groq/llama-3.1-8b-instant', 'stripped_model_name': 'llama-3.1-8b-instant', 'combined_stripped_model_name': 'groq/llama-3.1-8b-instant', 'custom_llm_provider': 'groq'}
13:33:40 - LiteLLM:DEBUG: utils.py:5605 - checking potential_model_names in litellm.model_cost: {'split_model': 'llama-3.1-8b-instant', 'combined_model_name': 'groq/llama-3.1-8b-instant', 'stripped_model_name': 'llama-3.1-8b-instant', 'combined_stripped_model_name': 'groq/llama-3.1-8b-instant', 'custom_llm_provider': 'groq'}
13:33:40 - LiteLLM:DEBUG: utils.py:5605 - checking potential_model_names in litellm.model_cost: {'split_model': 'llama-3.1-8b-instant', 'combined_model_name': 'groq/llama-3.1-8b-instant', 'stripped_model_name': 'llama-3.1-8b-instant', 'combined_stripped_model_name': 'groq/llama-3.1-8b-instant', 'custom_llm_provider': 'groq'}
13:33:40 - LiteLLM:DEBUG: utils.py:5605 - checking potential_model_names in litellm.model_cost: {'split_model': 'llama-3.1-8b-instant', 'combined_model_name': 'groq/llama-3.1-8b-instant', 'stripped_model_name': 'llama-3.1-8b-instant', 'combined_stripped_model_name': 'groq/llama-3.1-8b-instant', 'custom_llm_provider': 'groq'}
13:33:40 - LiteLLM:DEBUG: litellm_logging.py:1540 - response_cost: 2.09e-06

OK.

13:33:40 - LiteLLM:DEBUG: litellm_logging.py:1540 - response_cost: 2.09e-06
13:33:40 - LiteLLM:DEBUG: utils.py:5605 - checking potential_model_names in litellm.model_cost: {'split_model': 'llama-3.1-8b-instant', 'combined_model_name': 'groq/llama-3.1-8b-instant', 'stripped_model_name': 'llama-3.1-8b-instant', 'combined_stripped_model_name': 'groq/llama-3.1-8b-instant', 'custom_llm_provider': 'groq'}
13:33:40 - LiteLLM:DEBUG: utils.py:5605 - checking potential_model_names in litellm.model_cost: {'split_model': 'llama-3.1-8b-instant', 'combined_model_name': 'groq/llama-3.1-8b-instant', 'stripped_model_name': 'llama-3.1-8b-instant', 'combined_stripped_model_name': 'groq/llama-3.1-8b-instant', 'custom_llm_provider': 'groq'}

In [17]:
import litellm
import warnings
warnings.filterwarnings("ignore", category=UserWarning)

os.environ["GROQ_API_KEY"] = os.environ.get("GROQ_API_KEY_2", "")
print(f"Key loaded: {bool(os.environ.get('GROQ_API_KEY_2'))}")

# ── Option 1: Tell LiteLLM to auto-retry with backoff ─────────────────────
litellm.num_retries = 5
litellm.retry_after = 10  # wait 10s between retries

eval_dataset = Dataset.from_pandas(
    eval_df,
    data_definition=DataDefinition(),
    descriptors=[
        Sentiment("answer", alias="Sentiment"),
        TextLength("answer", alias="Length"),
        DeclineLLMEval(
            "answer",
            alias="Denials",
            provider="litellm",
            model="groq/llama-3.3-70b-versatile"
        ),
    ]
)

eval_dataset.as_dataframe()

13:36:14 - LiteLLM:DEBUG: utils.py:481 -

13:36:14 - LiteLLM:DEBUG: utils.py:481 - Request to litellm:
13:36:14 - LiteLLM:DEBUG: utils.py:481 - litellm.acompletion(model='groq/llama-3.3-70b-versatile', custom_llm_provider=None, messages=[{'role': 'system', 'content': 'You are a judge which evaluates text.'}, {'role': 'user', 'content': 'A "DECLINE" typically refers to a refusal or a polite rejection to do something.\nIn these contexts, "DECLINE" signifies a respectful or formal way of saying no to provide a help, service, or answer.\nClassify text between ___text_starts_here___ and ___text_ends_here___ into two categories: DECLINE and OK.\n___text_starts_here___\nTo determine the fraud detection rate in the dataset, we need to look at the statistics provided. The fraud rate is explicitly mentioned in the KEY METRICS section:\n\n- Fraud Rate: 3.32%\n\nThis means that out of the total records (10,000), 3.32% of the customers are identified as fraudulent. To find the number of fraudulent customers, we can calculate:\n\nNumber of fraudulent customers = Total Records * Fraud Rate\n= 10,000 * 3.32%\n= 10,000 * 0.0332\n= 332\n\nSo, there are 332 customers identified as fraudulent in the dataset. The fraud detection rate, in this case, refers to the proportion of customers that are correctly identified as fraudulent out of all the customers that are actually fraudulent. However, the provided dataset does not explicitly give us the true positives (correctly identified fraudulent customers) versus false negatives (fraudulent customers not identified as such) to directly calculate the detection rate or the precision and recall of the fraud detection system.\n\nGiven the information available, we can only state the fraud rate as 3.32%, which indicates the prevalence of fraud in the dataset, not the performance of a fraud detection model. For a detailed analysis of the fraud detection rate (including precision, recall, and F1 score), we would need more specific information about the true positives, false positives, true negatives, and false negatives resulting from a fraud detection model\'s predictions.\n___text_ends_here___\nUse the following categories for classification:\nDECLINE: if text is decline\nOK: if text is ok\nUNKNOWN: use this category only if the information provided is not sufficient to make a clear determination\n\n\nThink step by step.\nReturn category, reasoning formatted as json without formatting as follows:\n{\n"category": "DECLINE or OK or UNKNOWN"\n"reasoning": "<reasoning here>"\n}'}], api_key=None, api_base=None, seed=None)
13:36:14 - LiteLLM:DEBUG: utils.py:481 -

13:36:14 - LiteLLM:DEBUG: utils.py:1007 - Removing thought signatures from tool call IDs for non-Gemini model
13:36:14 - LiteLLM:DEBUG: litellm_logging.py:557 - self.optional_params: {}
13:36:14 - LiteLLM:DEBUG: utils.py:481 - ASYNC kwargs[caching]: False; litellm.cache: None; kwargs.get('cache'): None
13:36:14 - LiteLLM:DEBUG: main.py:525 - 🔄 NO SHARED SESSION: acompletion called without shared_session
13:36:14 - LiteLLM:DEBUG: utils.py:481 -

13:36:14 - LiteLLM:DEBUG: utils.py:5605 - checking potential_model_names in litellm.model_cost: {'split_model': 'llama-3.3-70b-versatile', 'combined_model_name': 'groq/llama-3.3-70b-versatile', 'stripped_model_name': 'llama-3.3-70b-versatile', 'combined_stripped_model_name': 'groq/llama-3.3-70b-versatile', 'custom_llm_provider': 'groq'}
13:36:14 - LiteLLM:DEBUG: utils.py:481 - Request to litellm:
13:36:14 - LiteLLM:DEBUG: utils.py:5605 - checking potential_model_names in litellm.model_cost: {'split_model': 'llama-3.3-70b-versatile', 'combined_model_name': 'groq/llama-3.3-70b-versatile', 'stripped_model_name': 'llama-3.3-70b-versatile', 'combined_stripped_model_name': 'groq/llama-3.3-70b-versatile', 'custom_llm_provider': 'groq'}
13:36:14 - LiteLLM:INFO: utils.py:4004 -
LiteLLM completion() model= llama-3.3-70b-versatile; provider = groq
13:36:14 - LiteLLM:DEBUG: utils.py:481 - litellm.acompletion(model='groq/llama-3.3-70b-versatile', custom_llm_provider=None, messages=[{'role': 'system', 'content': 'You are a judge which evaluates text.'}, {'role': 'user', 'content': 'A "DECLINE" typically refers to a refusal or a polite rejection to do something.\nIn these contexts, "DECLINE" signifies a respectful or formal way of saying no to provide a help, service, or answer.\nClassify text between ___text_starts_here___ and ___text_ends_here___ into two categories: DECLINE and OK.\n___text_starts_here___\nTo determine which ML model performs best for credit default prediction, we need to analyze the given dataset statistics. The problem of credit default prediction can be viewed as a classification problem where we aim to predict whether a customer will default on their credit (i.e., commit fraud) based on various features.\n\nGiven the dataset statistics, we notice that the target variable \'Fraud\' has a rate of 3.32%, indicating an imbalanced dataset. In such cases, models like XGBoost and Random Forest tend to outperform logistic regression.\n\nFrom the correlation analysis with \'Fraud\', we see that the top features correlated with fraud are \'Exited\', \'ComplainFlag\', \'Complain\', \'OperationalRiskScore\', and \'RiskScore\', with correlation coefficients of 0.292838, 0.292243, 0.292243, 0.283743, and 0.223436, respectively.\n\nWhile the dataset statistics do not provide direct performance metrics (e.g., accuracy, precision, recall, F1-score, ROC-AUC) for different ML models, the hint provided suggests that XGBoost and Random Forest tend to outperform logistic regression on imbalanced datasets.\n\nBased on this information, we can infer that XGBoost and Random Forest are likely to perform better than logistic regression for credit default prediction. However, without explicit performance metrics, it\'s challenging to determine which one performs best between XGBoost and Random Forest.\n\nAssuming that the performance of these models follows the general trend observed in imbalanced datasets, we can make an educated guess. XGBoost, being an ensemble model that combines multiple weak models to create a strong predictive model, often performs well in handling imbalanced datasets and complex interactions between features.\n\nTherefore, based on the provided dataset statistics and the context hint, XGBoost is likely to be a top-performing model for credit default prediction, but the actual performance may vary depending on the specific implementation, hyperparameter tuning, and evaluation metrics used. \n\nTo give a more precise answer, we would need the results of the models\' performance on a test set, which is not provided in the dataset statistics. However, if we had to choose based on the information given and general trends in machine learning, XGBoost would be a reasonable choice for handling the imbalanced \'Fraud\' classification problem. \n\nIn terms of numbers, we know that 3.32% of the customers are fraudsters, and we have a total of 10,000 records. This translates to approximately 332 fraud cases (0.0332 * 10,000). The performance of the model would be evaluated based on its ability to correctly identify these 332 cases while minimizing false positives. \n\nGiven the imbalanced nature of the dataset, it\'s essential to use appropriate evaluation metrics, such as precision, recall, F1-score, and ROC-AUC, to assess the model\'s performance. However, without explicit results, we can only speculate about the relative performance of different models based on their characteristics and the dataset statistics provided.\n___text_ends_here___\nUse the following categories for classification:\nDECLINE: if text is decline\nOK: if text is ok\nUNKNOWN: use this category only if the information provided is not sufficient to make a clear determination\n\n\nThink step by step.\nReturn category, reasoning formatted as json without formatting as follows:\n{\n"category": "DECLINE or OK or UNKNOWN"\n"reasoning": "<reasoning here>"\n}'}], api_key=None, api_base=None, seed=None)
13:36:14 - LiteLLM:DEBUG: utils.py:4007 -
LiteLLM: Params passed to completion() {'model': 'llama-3.3-70b-versatile', 'functions': None, 'function_call': None, 'temperature': None, 'top_p': None, 'n': None, 'stream': None, 'stream_options': None, 'stop': None, 'max_tokens': None, 'max_completion_tokens': None, 'modalities': None, 'prediction': None, 'audio': None, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': None, 'user': None, 'custom_llm_provider': 'groq', 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None, 'max_retries': None, 'logprobs': None, 'top_logprobs': None, 'extra_headers': None, 'api_version': None, 'parallel_tool_calls': None, 'drop_params': None, 'allowed_openai_params': None, 'reasoning_effort': None, 'verbosity': None, 'additional_drop_params': None, 'messages': [{'role': 'system', 'content': 'You are a judge which evaluates text.'}, {'role': 'user', 'content': 'A "DECLINE" typically refers to a refusal or a polite rejection to do something.\nIn these contexts, "DECLINE" signifies a respectful or formal way of saying no to provide a help, service, or answer.\nClassify text between ___text_starts_here___ and ___text_ends_here___ into two categories: DECLINE and OK.\n___text_starts_here___\nTo determine the fraud detection rate in the dataset, we need to look at the statistics provided. The fraud rate is explicitly mentioned in the KEY METRICS section:\n\n- Fraud Rate: 3.32%\n\nThis means that out of the total records (10,000), 3.32% of the customers are identified as fraudulent. To find the number of fraudulent customers, we can calculate:\n\nNumber of fraudulent customers = Total Records * Fraud Rate\n= 10,000 * 3.32%\n= 10,000 * 0.0332\n= 332\n\nSo, there are 332 customers identified as fraudulent in the dataset. The fraud detection rate, in this case, refers to the proportion of customers that are correctly identified as fraudulent out of all the customers that are actually fraudulent. However, the provided dataset does not explicitly give us the true positives (correctly identified fraudulent customers) versus false negatives (fraudulent customers not identified as such) to directly calculate the detection rate or the precision and recall of the fraud detection system.\n\nGiven the information available, we can only state the fraud rate as 3.32%, which indicates the prevalence of fraud in the dataset, not the performance of a fraud detection model. For a detailed analysis of the fraud detection rate (including precision, recall, and F1 score), we would need more specific information about the true positives, false positives, true negatives, and false negatives resulting from a fraud detection model\'s predictions.\n___text_ends_here___\nUse the following categories for classification:\nDECLINE: if text is decline\nOK: if text is ok\nUNKNOWN: use this category only if the information provided is not sufficient to make a clear determination\n\n\nThink step by step.\nReturn category, reasoning formatted as json without formatting as follows:\n{\n"category": "DECLINE or OK or UNKNOWN"\n"reasoning": "<reasoning here>"\n}'}], 'thinking': None, 'web_search_options': None, 'safety_identifier': None, 'service_tier': None}
13:36:14 - LiteLLM:DEBUG: utils.py:481 -

13:36:14 - LiteLLM:DEBUG: utils.py:4010 -
LiteLLM: Non-Default params passed to completion() {}
13:36:14 - LiteLLM:DEBUG: utils.py:1007 - Removing thought signatures from tool call IDs for non-Gemini model
13:36:14 - LiteLLM:DEBUG: utils.py:5605 - checking potential_model_names in litellm.model_cost: {'split_model': 'llama-3.3-70b-versatile', 'combined_model_name': 'groq/llama-3.3-70b-versatile', 'stripped_model_name': 'llama-3.3-70b-versatile', 'combined_stripped_model_name': 'groq/llama-3.3-70b-versatile', 'custom_llm_provider': 'groq'}
13:36:14 - LiteLLM:DEBUG: litellm_logging.py:557 - self.optional_params: {}
13:36:14 - LiteLLM:DEBUG: utils.py:481 - Final returned optional params: {'extra_body': {}}
13:36:14 - LiteLLM:DEBUG: utils.py:481 - ASYNC kwargs[caching]: False; litellm.cache: None; kwargs.get('cache'): None
13:36:14 - LiteLLM:DEBUG: litellm_logging.py:557 - self.optional_params: {'extra_body': {}}
13:36:14 - LiteLLM:DEBUG: main.py:525 - 🔄 NO SHARED SESSION: acompletion called without shared_session
13:36:14 - LiteLLM:DEBUG: utils.py:5605 - checking potential_model_names in litellm.model_cost: {'split_model': 'llama-3.3-70b-versatile', 'combined_model_name': 'groq/llama-3.3-70b-versatile', 'stripped_model_name': 'llama-3.3-70b-versatile', 'combined_stripped_model_name': 'groq/llama-3.3-70b-versatile', 'custom_llm_provider': 'groq'}
13:36:14 - LiteLLM:DEBUG: utils.py:481 -

13:36:14 - LiteLLM:DEBUG: utils.py:5605 - checking potential_model_names in litellm.model_cost: {'split_model': 'llama-3.3-70b-versatile', 'combined_model_name': 'groq/llama-3.3-70b-versatile', 'stripped_model_name': 'llama-3.3-70b-versatile', 'combined_stripped_model_name': 'groq/llama-3.3-70b-versatile', 'custom_llm_provider': 'groq'}
13:36:14 - LiteLLM:DEBUG: litellm_logging.py:1150 -

POST Request Sent from LiteLLM:
curl -X POST \
https://api.groq.com/openai/v1/chat/completions \
-H 'Authorization: Be****RT' -H 'Content-Type: application/json' \
-d '{'model': 'llama-3.3-70b-versatile', 'messages': [{'role': 'system', 'content': 'You are a judge which evaluates text.'}, {'role': 'user', 'content': 'A "DECLINE" typically refers to a refusal or a polite rejection to do something.\nIn these contexts, "DECLINE" signifies a respectful or formal way of saying no to provide a help, service, or answer.\nClassify text between ___text_starts_here___ and ___text_ends_here___ into two categories: DECLINE and OK.\n___text_starts_here___\nTo determine the fraud detection rate in the dataset, we need to look at the statistics provided. The fraud rate is explicitly mentioned in the KEY METRICS section:\n\n- Fraud Rate: 3.32%\n\nThis means that out of the total records (10,000), 3.32% of the customers are identified as fraudulent. To find the number of fraudulent customers, we can calculate:\n\nNumber of fraudulent customers = Total Records * Fraud Rate\n= 10,000 * 3.32%\n= 10,000 * 0.0332\n= 332\n\nSo, there are 332 customers identified as fraudulent in the dataset. The fraud detection rate, in this case, refers to the proportion of customers that are correctly identified as fraudulent out of all the customers that are actually fraudulent. However, the provided dataset does not explicitly give us the true positives (correctly identified fraudulent customers) versus false negatives (fraudulent customers not identified as such) to directly calculate the detection rate or the precision and recall of the fraud detection system.\n\nGiven the information available, we can only state the fraud rate as 3.32%, which indicates the prevalence of fraud in the dataset, not the performance of a fraud detection model. For a detailed analysis of the fraud detection rate (including precision, recall, and F1 score), we would need more specific information about the true positives, false positives, true negatives, and false negatives resulting from a fraud detection model\'s predictions.\n___text_ends_here___\nUse the following categories for classification:\nDECLINE: if text is decline\nOK: if text is ok\nUNKNOWN: use this category only if the information provided is not sufficient to make a clear determination\n\n\nThink step by step.\nReturn category, reasoning formatted as json without formatting as follows:\n{\n"category": "DECLINE or OK or UNKNOWN"\n"reasoning": "<reasoning here>"\n}'}]}'


13:36:14 - LiteLLM:DEBUG: utils.py:481 - Request to litellm:
13:36:14 - LiteLLM:DEBUG: utils.py:5605 - checking potential_model_names in litellm.model_cost: {'split_model': 'llama-3.3-70b-versatile', 'combined_model_name': 'groq/llama-3.3-70b-versatile', 'stripped_model_name': 'llama-3.3-70b-versatile', 'combined_stripped_model_name': 'groq/llama-3.3-70b-versatile', 'custom_llm_provider': 'groq'}

Key loaded: True

13:36:14 - LiteLLM:DEBUG: litellm_logging.py:1223 - RAW RESPONSE:
{"id": "chatcmpl-bc6846d6-20ef-4579-946c-91ca0aa837f6", "object": "chat.completion", "created": 1775799375, "model": "llama-3.3-70b-versatile", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\"category\": \"DECLINE\", \"reasoning\": \"The text politely refuses to provide a detailed analysis of the fraud detection rate, stating that more specific information is needed to calculate precision, recall, and F1 score, which signifies a respectful or formal way of saying no to provide a help or service.\"}"}, "logprobs": null, "finish_reason": "stop"}], "usage": {"queue_time": 0.044776289, "prompt_tokens": 502, "prompt_time": 0.03404223, "completion_tokens": 64, "completion_time": 0.183386737, "total_tokens": 566, "total_time": 0.217428967}, "usage_breakdown": null, "system_fingerprint": "fp_dae98b5ecb", "x_groq": {"id": "req_01knty855eekasmv2dg764jb02", "seed": 1154431542}, "service_tier": "on_demand"}


13:36:14 - LiteLLM:DEBUG: litellm_logging.py:3292 - Filtered callbacks: []
13:36:14 - LiteLLM:DEBUG: cost_calculator.py:1130 - selected model name for cost calculation: groq/llama-3.3-70b-versatile
13:36:14 - LiteLLM:DEBUG: litellm_logging.py:1540 - response_cost: 0.00034674
13:36:14 - LiteLLM:DEBUG: utils.py:481 - Async Wrapper: Completed Call, calling async_success_handler: <bound method Logging.async_success_handler of <litellm.litellm_core_utils.litellm_logging.Logging object at 0x3258dd650>>
13:36:14 - LiteLLM:DEBUG: litellm_logging.py:3292 - Filtered callbacks: []
13:36:14 - LiteLLM:DEBUG: utils.py:481 - Logging Details LiteLLM-Async Success Call, cache_hit=None
13:36:15 - LiteLLM:DEBUG: litellm_logging.py:1223 - RAW RESPONSE:
{"id": "chatcmpl-231977ca-02b5-43fc-a1a9-af53b8b8a050", "object": "chat.completion", "created": 1775799375, "model": "llama-3.3-70b-versatile", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\"category\": \"OK\", \"reasoning\": \"The text does not contain any refusal or rejection, but rather provides information and analysis about the class imbalance issue in a fraud detection dataset, suggesting potential techniques to improve the detection of fraudulent transactions.\"}"}, "logprobs": null, "finish_reason": "stop"}], "usage": {"queue_time": 0.046340147, "prompt_tokens": 506, "prompt_time": 0.071497851, "completion_tokens": 51, "completion_time": 0.168691696, "total_tokens": 557, "total_time": 0.240189547}, "usage_breakdown": null, "system_fingerprint": "fp_dae98b5ecb", "x_groq": {"id": "req_01knty855jekb90e3t63r12m73", "seed": 1766460833}, "service_tier": "on_demand"}


13:36:15 - LiteLLM:DEBUG: litellm_logging.py:3292 - Filtered callbacks: []
13:36:15 - LiteLLM:DEBUG: cost_calculator.py:1130 - selected model name for cost calculation: groq/llama-3.3-70b-versatile
13:36:15 - LiteLLM:DEBUG: litellm_logging.py:1540 - response_cost: 0.00033883
13:36:15 - LiteLLM:DEBUG: utils.py:481 - Async Wrapper: Completed Call, calling async_success_handler: <bound method Logging.async_success_handler of <litellm.litellm_core_utils.litellm_logging.Logging object at 0x325efbd10>>
13:36:15 - LiteLLM:DEBUG: litellm_logging.py:3292 - Filtered callbacks: []
13:36:15 - LiteLLM:DEBUG: litellm_logging.py:1223 - RAW RESPONSE:
{"id": "chatcmpl-dc9a124a-e93d-438e-9fd2-7c308003c6b7", "object": "chat.completion", "created": 1775799375, "model": "llama-3.3-70b-versatile", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\"category\": \"OK\", \"reasoning\": \"The text does not contain a refusal or polite rejection, but rather provides an analysis and suggestions to reduce the churn rate, indicating a positive and helpful tone.\"}"}, "logprobs": null, "finish_reason": "stop"}], "usage": {"queue_time": 0.045361786, "prompt_tokens": 591, "prompt_time": 0.071409132, "completion_tokens": 44, "completion_time": 0.171901217, "total_tokens": 635, "total_time": 0.243310349}, "usage_breakdown": null, "system_fingerprint": "fp_dae98b5ecb", "x_groq": {"id": "req_01knty855aekatpagqc5tw3w2d", "seed": 176116348}, "service_tier": "on_demand"}


13:36:15 - LiteLLM:DEBUG: litellm_logging.py:3292 - Filtered callbacks: []
13:36:15 - LiteLLM:DEBUG: cost_calculator.py:1130 - selected model name for cost calculation: groq/llama-3.3-70b-versatile
13:36:15 - LiteLLM:DEBUG: litellm_logging.py:1540 - response_cost: 0.00038344999999999997
13:36:15 - LiteLLM:DEBUG: utils.py:481 - Async Wrapper: Completed Call, calling async_success_handler: <bound method Logging.async_success_handler of <litellm.litellm_core_utils.litellm_logging.Logging object at 0x325465b50>>
13:36:15 - LiteLLM:DEBUG: litellm_logging.py:3292 - Filtered callbacks: []
13:36:15 - LiteLLM:DEBUG: utils.py:481 - Logging Details LiteLLM-Async Success Call, cache_hit=None
13:36:15 - LiteLLM:DEBUG: utils.py:481 - Logging Details LiteLLM-Async Success Call, cache_hit=None
13:36:15 - LiteLLM:DEBUG: litellm_logging.py:1223 - RAW RESPONSE:
{"id": "chatcmpl-cf4a5260-1068-4b8f-9e12-3a8eb847d259", "object": "chat.completion", "created": 1775799375, "model": "llama-3.3-70b-versatile", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\"category\": \"OK\", \"reasoning\": \"The text does not contain a refusal or polite rejection to do something, but rather a detailed analysis of handling missing values in operational banking data while preserving regulatory compliance and avoiding synthetic bias, providing various strategies for imputation and considerations for each approach.\"}"}, "logprobs": null, "finish_reason": "stop"}], "usage": {"queue_time": 0.045807446, "prompt_tokens": 1039, "prompt_time": 0.065576994, "completion_tokens": 61, "completion_time": 0.231345334, "total_tokens": 1100, "total_time": 0.296922328}, "usage_breakdown": null, "system_fingerprint": "fp_dae98b5ecb", "x_groq": {"id": "req_01knty8561fmpb6r128rpptzdz", "seed": 364565244}, "service_tier": "on_demand"}


13:36:15 - LiteLLM:DEBUG: litellm_logging.py:3292 - Filtered callbacks: []
13:36:15 - LiteLLM:DEBUG: cost_calculator.py:1130 - selected model name for cost calculation: groq/llama-3.3-70b-versatile
13:36:15 - LiteLLM:DEBUG: litellm_logging.py:1540 - response_cost: 0.0006612
13:36:15 - LiteLLM:DEBUG: utils.py:481 - Async Wrapper: Completed Call, calling async_success_handler: <bound method Logging.async_success_handler of <litellm.litellm_core_utils.litellm_logging.Logging object at 0x3258dcc90>>
13:36:15 - LiteLLM:DEBUG: litellm_logging.py:3292 - Filtered callbacks: []
13:36:15 - LiteLLM:DEBUG: utils.py:481 - Logging Details LiteLLM-Async Success Call, cache_hit=None
13:36:15 - LiteLLM:DEBUG: litellm_logging.py:1223 - RAW RESPONSE:
{"id": "chatcmpl-2769c01b-eb27-45c9-9373-ce43c33c6ccb", "object": "chat.completion", "created": 1775799375, "model": "llama-3.3-70b-versatile", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\"category\": \"OK\", \"reasoning\": \"The text does not contain a refusal or polite rejection, but rather a detailed analysis and discussion about determining which ML model performs best for credit default prediction, providing insights and educated guesses based on the dataset statistics and general trends in machine learning.\"}"}, "logprobs": null, "finish_reason": "stop"}], "usage": {"queue_time": 0.04582177, "prompt_tokens": 823, "prompt_time": 0.08753006, "completion_tokens": 60, "completion_time": 0.243172131, "total_tokens": 883, "total_time": 0.330702191}, "usage_breakdown": null, "system_fingerprint": "fp_dae98b5ecb", "x_groq": {"id": "req_01knty855qfhkb9420p6tx8da0", "seed": 513416416}, "service_tier": "on_demand"}


13:36:15 - LiteLLM:DEBUG: litellm_logging.py:3292 - Filtered callbacks: []
13:36:15 - LiteLLM:DEBUG: cost_calculator.py:1130 - selected model name for cost calculation: groq/llama-3.3-70b-versatile
13:36:15 - LiteLLM:DEBUG: litellm_logging.py:1540 - response_cost: 0.0005329699999999999
13:36:15 - LiteLLM:DEBUG: utils.py:481 - Async Wrapper: Completed Call, calling async_success_handler: <bound method Logging.async_success_handler of <litellm.litellm_core_utils.litellm_logging.Logging object at 0x325e67990>>
13:36:15 - LiteLLM:DEBUG: litellm_logging.py:3292 - Filtered callbacks: []
13:36:15 - LiteLLM:DEBUG: utils.py:481 - Logging Details LiteLLM-Async Success Call, cache_hit=None

                                                            question  \
0                   What is the fraud detection rate in the dataset?
1        Which ML model performs best for credit default prediction?
2  How should missing values be handled in operational banking data?
3                  What is the churn rate and how can it be reduced?
4              Explain the class imbalance issue in fraud detection.

                                                                                    context  \
0  Fraud detection in banking uses ML classifiers. Precision-recall tradeoffs are critical.
1          XGBoost and Random Forest outperform logistic regression on imbalanced datasets.
2          Imputation must preserve regulatory compliance and not introduce synthetic bias.
3                                Customer churn in retail banking averages 15-20% annually.
4                        Fraud datasets are heavily imbalanced with fraud rates below 1-2%.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  answer  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        To determine the fraud detection rate in the dataset, we need to look at the statistics provided. The fraud rate is explicitly mentioned in the KEY METRICS section:\n\n- Fraud Rate: 3.32%\n\nThis means that out of the total records (10,000), 3.32% of the customers are identified as fraudulent. To find the number of fraudulent customers, we can calculate:\n\nNumber of fraudulent customers = Total Records * Fraud Rate\n= 10,000 * 3.32%\n= 10,000 * 0.0332\n= 332\n\nSo, there are 332 customers identified as fraudulent in the dataset. The fraud detection rate, in this case, refers to the proportion of customers that are correctly identified as fraudulent out of all the customers that are actually fraudulent. However, the provided dataset does not explicitly give us the true positives (correctly identified fraudulent customers) versus false negatives (fraudulent customers not identified as such) to directly calculate the detection rate or the precision and recall of the fraud detection system.\n\nGiven the information available, we can only state the fraud rate as 3.32%, which indicates the prevalence of fraud in the dataset, not the performance of a fraud detection model. For a detailed analysis of the fraud detection rate (including precision, recall, and F1 score), we would need more specific information about the true positives, false positives, true negatives, and false negatives resulting from a fraud detection model's predictions.
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  To determine which ML model performs best for credit default prediction, we need to analyze the given dataset statistics. The problem of credit default prediction can be viewed as a classification problem where we aim to predict whether a customer will default on their credit (i.e., commit fraud) based on various features.\n\nGiven the dataset statistics, we notice that the target variable 'Fraud' has a rate of 3.32%, indicating an imbalanced dataset. In such cases, models like XGBoost and Random Forest tend to outperform logistic regression.\n\nFrom the correlation analysis with 'Fraud', we see that the top features correlated with fraud are 'Exited', 'ComplainFlag', 'Complain', 'OperationalRiskScore', and 'RiskScore', with correlation coefficients of 0.292838, 0.292243, 0.292243, 0.283743, and 0.223436, respectively.\n\nWhile the dataset statistics do not provide direct performance metrics (e.g., accuracy, precision, recall, F1-score, ROC-AUC) for different ML models, the hint provided suggests that XGBoost and Random Forest tend to outperform logistic regression on imbalanced datasets.\n\nBased on this information, we can infer that XGBoost and Random Forest are likely to perform better than logistic regression for credit default prediction. However, without explicit performance metrics, it's challenging to determine which one performs best between XGBoost and Random Forest.\n\nAssuming that the performance of these models follows the general trend observed in imbalanced datasets, we can make an educated guess. XGBoost, being an ensemble model that combines multiple weak models to create a strong predictive model, often performs well in handling imbalanced datasets and complex interactions between features.\n\nTherefore, based on the provided dataset statistics and the context hint, XGBoost is likely to be a top-performing model for credit default prediction, but the actual performance may vary depending on the specific implementation, hyperparameter tuning, and evaluation metrics used. \n\nTo give a more precise answer, we would need the results of the models' performance on a test set, which is not provided in the dataset statistics. However, if we had to choose based on the information given and general trends in machine learning, XGBoost would be a reasonable choice for handling the imbalanced 'Fraud' classification problem. \n\nIn terms of numbers, we know that 3.32% of the customers are fraudsters, and we have a total of 10,000 records. This translates to approximately 332 fraud cases (0.0332 * 10,000). The performance of the model would be evaluated based on its ability to correctly identify these 332 cases while minimizing false positives. \n\nGiven the imbalanced nature of the dataset, it's essential to use appropriate evaluation metrics, such as precision, recall, F1-score, and ROC-AUC, to assess the model's performance. However, without explicit results, we can only speculate about the relative performance of different models based on their characteristics and the dataset statistics provided.
2  To handle missing values in operational banking data while preserving regulatory compliance and avoiding synthetic bias, we should consider the characteristics of the data and the implications of different imputation strategies. Based on the provided dataset statistics:\n\n1. **Mean and Standard Deviation**: Many features have a relatively large standard deviation compared to their mean, indicating a potential for outliers and skewness in the data. This suggests that mean or median imputation might not be suitable for all features.\n\n2. **Distribution of Categorical Variables**: The distribution of categorical variables like Geography, Gender, and Card Type shows a mix of balanced and imbalanced classes. For example, Geography has a relatively balanced distribution (France: 50.14%, Germany: 25.09%, Spain: 24.77%), while Card Type is also somewhat balanced. This balance is important to maintain when imputing missing values to avoid introducing bias.\n\n3. **Correlation with Fraud and Churn**: The features most correlated with Fraud and Churn (Exited) are largely related to customer behavior and risk assessment (e.g., Exited, ComplainFlag, OperationalRiskScore, RiskScore). Imputation strategies should preserve these relationships to maintain the integrity of risk and churn models.\n\n4. **Key Metrics**: The dataset has a Fraud Rate of 3.32%, a Churn Rate of 20.38%, and an average Credit Score of 650.53. These metrics indicate the importance of accurately modeling customer behavior and risk.\n\nGiven these considerations, here are some strategies for handling missing values:\n\n- **Listwise Deletion**: For features with very few missing values (less than 1%), listwise deletion might be acceptable, especially if the missing values are missing completely at random (MCAR). However, this approach risks bias if the missing values are not MCAR.\n\n- **Mean/Median Imputation**: For numerical features with a relatively small standard deviation and no significant outliers (e.g., Age, with a mean of 38.92 and a standard deviation of 10.49), mean or median imputation could be appropriate. For example, imputing the mean Age (38.92) for missing Age values might be reasonable.\n\n- **Regression Imputation**: For features highly correlated with others (e.g., RiskScore with OperationalRiskScore), using a regression model to predict missing values based on correlated features could be effective. This method can help preserve the relationships between features.\n\n- **K-Nearest Neighbors (KNN) Imputation**: This method involves finding similar data points (based on other features) to a row with a missing value and imputing the missing value with the mean or median of those similar points. It can be particularly useful for categorical variables or when the relationship between features is complex.\n\n- **Multiple Imputation**: Creating multiple versions of the dataset with different imputations for missing values and then analyzing each version to account for the uncertainty introduced by imputation. This approach is more complex but provides a way to quantify the impact of missing data on analysis results.\n\nFor this dataset, given the regulatory compliance and bias avoidance requirements, a combination of these strategies could be employed, tailored to the specific characteristics of each feature. For instance:\n\n- For the 'CreditScore' feature, which has a mean of 650.53 and a standard deviation of 96.65, mean imputation might be suitable due to its central tendency and variability.\n- For 'Geography', given its categorical nature and the need to preserve class balance, a random imputation based on the observed class distribution (e.g., 50.14% France, 25.09% Germany, 24.77% Spain) could be used.\n- For features highly correlated with Fraud or Churn, like 'ComplainFlag' or 'RiskScore', regression imputation or KNN imputation could be more appropriate to maintain these critical relationships.\n\nUltimately, the choice of imputation method should be guided by the specific analysis goals, the nature of the missing data (MCAR, MAR, or MNAR), and the need to preserve regulatory compliance and avoid introducing synthetic bias.

## Deploy to evidentlyAI UI Dashboard

In [18]:
from evidently.ui.workspace import DashboardPanelPlot, DashboardModel, DashboardTabModel
from evidently.sdk.models import PanelMetric

# 1. Define panels with correct PanelMetric fields
panel_sentiment = DashboardPanelPlot(
    title="Answer Sentiment",
    size="full",
    values=[
        PanelMetric(
            metric="Sentiment",
            legend="Sentiment Score",
        )
    ],
    plot_params={"plot_type": "line"}
)

panel_length = DashboardPanelPlot(
    title="Answer Text Length",
    size="full",
    values=[
        PanelMetric(
            metric="Denials",
            legend="Denial Rate"
        )
    ],
    plot_params={"plot_type": "bar"}
)

panel_denials = DashboardPanelPlot(
    title="LLM Denial Rate",
    size="full",
    values=[
        PanelMetric(
            metric="Denials",
            legend="Denial Rate"
        )
    ],
    plot_params={"plot_type": "bar"}
)

# 2. Create tab grouping all panels
tab = DashboardTabModel(
    title="LLM Audit Overview",
    panels=[panel_sentiment.id, panel_length.id, panel_denials.id]
)

# 3. Build dashboard model
dashboard = DashboardModel(
    tabs=[tab],
    panels=[panel_sentiment, panel_length, panel_denials]
)

# 4. Push to Evidently Cloud
ws.save_dashboard(project.id, dashboard)
print("✅ Dashboard saved to Evidently Cloud")
print(f"🔗 https://app.evidently.cloud/projects/{project.id}/dashboard")

✅ Dashboard saved to Evidently Cloud
🔗 https://app.evidently.cloud/projects/019d7204-9bfc-76e9-8c54-ee541e230e6f/dashboard

In [19]:
from evidently.ui.workspace import Workspace

# ── 1. Connect to local workspace ──────────────────────────────────────────
local_ws = Workspace.create("./evidently_workspace")

# ── 2. Check what projects actually exist locally ──────────────────────────
local_projects = local_ws.list_projects()
print(f"Local projects: {len(local_projects)}")
for p in local_projects:
    print(f"  Name: {p.name}, ID: {p.id}")

Local projects: 4
  Name: LLM Audit, ID: 019d75dd-1aa2-702d-9fe2-bc40f68caf49
  Name: LLM Audit, ID: 019d75e0-4a18-749e-a3a0-169182d86cec
  Name: LLM Audit, ID: 019d75e2-4b0f-7b9d-84fc-98e156cc524e
  Name: LLM Audit, ID: 019d75e0-da8c-7f52-9f1f-cf5ac080fa90

In [20]:
# ── 3. Create fresh local project ─────────────────────────────────────────
local_project = local_ws.create_project("LLM Audit")
local_project.description = "Project for auditing LLM performance on models, data, and LLMs evaluations."
local_project.save()
print(f"✅ Local project created: {local_project.id}")

# ── 4. Run report ──────────────────────────────────────────────────────────
report = Report(
    metrics=[TextEvals(columns=["answer"])],
    tags=["LLM-Audit", "groq", "Banking"]
)
snapshot = report.run(current_data=eval_dataset)
print("✅ Report ran")

# ── 5. Upload snapshot locally ─────────────────────────────────────────────
local_ws.add_run(local_project.id, snapshot)
print("✅ Snapshot uploaded locally")

# ── 6. Print correct local URL ─────────────────────────────────────────────
print(f"\n🔗 Go to: http://localhost:8080")
print(f"   Then click 'LLM Audit' project")
print(f"   Local project ID: {local_project.id}")

✅ Local project created: 019d75e4-50a0-7e76-826d-f37abd835f9f
✅ Report ran
✅ Snapshot uploaded locally

🔗 Go to: http://localhost:8080
   Then click 'LLM Audit' project
   Local project ID: 019d75e4-50a0-7e76-826d-f37abd835f9f